# Generated by Django 5.1.4 on 2024-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trsapp', '0002_user_model_feedback_model_complaint_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
